# Generated by Django 4.2.7 on 2023-11-06 02:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='freelancerprofile',
            name='ratings',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Your average rating', max_digits=3, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AddField(
            model_name='freelancerprofile',
            name='reviews',
            field=models.TextField(blank=True, help_text='Customer reviews'),
        ),
        migrations.AddField(
            model_name='freelancerprofile',
            name='skills',
            field=models.TextField(blank=True, help_text='List your skills separated by commas'),
        ),
        migrations.AlterField(
            model_name='freelancerprofile',
            name='portfolio',
            field=models.URLField(blank=True, help_text='Link to your professional portfolio'),
        ),
    ]
